A1 [原始行号:596] http://91.33.100.187:5001/v1/models -> Error: HTTPConnectionPool(host='91.33.100.187', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C89A0>, 'Connection to 91.33.100.187 timed out. (connect timeout=5)'))
A2 [原始行号:588] http://91.63.167.135:5001/v1/models -> Error: HTTPConnectionPool(host='91.63.167.135', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA610>, 'Connection to 91.63.167.135 timed out. (connect timeout=5)'))
A3 [原始行号:208] http://175.0.135.91:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.135.91', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D35651F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A4 [原始行号:291] http://211.10.90.212:8880/v1/models -> Error: 404 Client Error: Not Found for url: http://211.10.90.212:8880/v1/models
A5 [原始行号:174] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A6 [原始行号:292] http://46.36.40.127:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://46.36.40.127:8080/v1/models
A7 [原始行号:711] http://61.231.193.249:5001/v1/models -> Error: HTTPConnectionPool(host='61.231.193.249', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA910>, 'Connection to 61.231.193.249 timed out. (connect timeout=5)'))
A8 [原始行号:210] http://94.226.100.13:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://94.226.100.13:5001/v1/models
A9 [原始行号:266] http://91.33.99.31:5001/v1/models -> Error: HTTPConnectionPool(host='91.33.99.31', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D2FB8A30>, 'Connection to 91.33.99.31 timed out. (connect timeout=5)'))
A10 [原始行号:331] http://91.37.90.1:5001/v1/models -> Error: HTTPConnectionPool(host='91.37.90.1', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8A30>, 'Connection to 91.37.90.1 timed out. (connect timeout=5)'))
A11 [原始行号:192] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A12 [原始行号:738] http://59.174.150.125:2000/v1/models -> Error: HTTPConnectionPool(host='59.174.150.125', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0370>, 'Connection to 59.174.150.125 timed out. (connect timeout=5)'))
A13 [原始行号:234] http://84.105.231.12:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://84.105.231.12:5001/v1/models
A14 [原始行号:626] http://84.135.35.23:5001/v1/models -> Error: HTTPConnectionPool(host='84.135.35.23', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DAA00>, 'Connection to 84.135.35.23 timed out. (connect timeout=5)'))
A15 [原始行号:768] http://91.56.80.234:5001/v1/models -> Error: HTTPConnectionPool(host='91.56.80.234', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DAFA0>, 'Connection to 91.56.80.234 timed out. (connect timeout=5)'))
A16 [原始行号:155] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A17 [原始行号:514] http://91.44.152.60:5001/v1/models -> Error: HTTPConnectionPool(host='91.44.152.60', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA850>, 'Connection to 91.44.152.60 timed out. (connect timeout=5)'))
A18 [原始行号:67] http://83.219.120.195:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://83.219.120.195:5001/v1/models
A19 [原始行号:196] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A20 [原始行号:109] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A21 [原始行号:66] http://62.238.152.48:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://62.238.152.48:5000/v1/models
A22 [原始行号:199] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A23 [原始行号:78] http://78.80.146.85:8008/v1/models ->   ✅ 成功：响应长度 78 字符
A24 [原始行号:470] http://209.122.132.208:8001/v1/models -> Error: 400 Client Error: Bad Request for url: http://209.122.132.208:8001/v1/models
A25 [原始行号:23] http://82.168.100.208:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://82.168.100.208:5001/v1/models
A26 [原始行号:338] http://217.121.20.62:8877/v1/models -> Error: HTTPConnectionPool(host='217.121.20.62', port=8877): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA250>, 'Connection to 217.121.20.62 timed out. (connect timeout=5)'))
A27 [原始行号:704] http://217.251.66.122:5001/v1/models -> Error: HTTPConnectionPool(host='217.251.66.122', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0CD0>, 'Connection to 217.251.66.122 timed out. (connect timeout=5)'))
A28 [原始行号:444] http://84.19.30.244:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.244:1207/v1/models
A29 [原始行号:405] http://77.248.176.58:5001/v1/models -> Error: HTTPConnectionPool(host='77.248.176.58', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0250>, 'Connection to 77.248.176.58 timed out. (connect timeout=5)'))
A30 [原始行号:39] http://84.29.194.37:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://84.29.194.37:5001/v1/models
A31 [原始行号:583] http://18.194.87.221:3000/v1/models -> Error: HTTPConnectionPool(host='18.194.87.221', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8B80>, 'Connection to 18.194.87.221 timed out. (connect timeout=5)'))
A32 [原始行号:86] http://13.232.231.39:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://13.232.231.39:8080/v1/models
A33 [原始行号:137] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A34 [原始行号:309] http://175.0.133.21:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.133.21', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D33B0DF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A35 [原始行号:525] http://175.0.135.198:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.135.198', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D33DAB20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A36 [原始行号:557] http://219.140.142.235:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.142.235', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35866D0>, 'Connection to 219.140.142.235 timed out. (connect timeout=5)'))
A37 [原始行号:231] http://83.108.114.183:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://83.108.114.183:5000/v1/models
A38 [原始行号:513] http://91.8.83.80:5001/v1/models -> Error: HTTPConnectionPool(host='91.8.83.80', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596040>, 'Connection to 91.8.83.80 timed out. (connect timeout=5)'))
A39 [原始行号:333] http://146.185.145.158:1337/v1/models -> Error: 404 Client Error: Not Found for url: http://146.185.145.158:1337/v1/models
A40 [原始行号:649] http://77.184.204.64:5001/v1/models -> Error: HTTPConnectionPool(host='77.184.204.64', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596910>, 'Connection to 77.184.204.64 timed out. (connect timeout=5)'))
A41 [原始行号:568] http://84.251.41.56:3000/v1/models -> Error: HTTPConnectionPool(host='84.251.41.56', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33ADDC0>, 'Connection to 84.251.41.56 timed out. (connect timeout=5)'))
A42 [原始行号:778] http://159.203.44.54:9801/v1/models -> Error: HTTPConnectionPool(host='159.203.44.54', port=9801): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DABB0>, 'Connection to 159.203.44.54 timed out. (connect timeout=5)'))
A43 [原始行号:118] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A44 [原始行号:650] http://61.231.194.185:5001/v1/models -> Error: HTTPConnectionPool(host='61.231.194.185', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35963D0>, 'Connection to 61.231.194.185 timed out. (connect timeout=5)'))
A45 [原始行号:215] http://84.31.160.101:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://84.31.160.101:5000/v1/models
A46 [原始行号:777] http://59.174.148.48:2000/v1/models -> Error: HTTPConnectionPool(host='59.174.148.48', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586640>, 'Connection to 59.174.148.48 timed out. (connect timeout=5)'))
A47 [原始行号:351] http://31.21.172.131:5001/v1/models -> Error: HTTPConnectionPool(host='31.21.172.131', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8EE0>, 'Connection to 31.21.172.131 timed out. (connect timeout=5)'))
A48 [原始行号:657] http://212.127.181.127:5000/v1/models -> Error: HTTPConnectionPool(host='212.127.181.127', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8880>, 'Connection to 212.127.181.127 timed out. (connect timeout=5)'))
A49 [原始行号:77] http://164.92.135.37:8080/v1/models ->   ✅ 成功：响应长度 265 字符
A50 [原始行号:689] http://59.174.148.143:2000/v1/models -> Error: HTTPConnectionPool(host='59.174.148.143', port=2000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D3586040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A51 [原始行号:326] http://148.66.155.177:444/v1/models -> Error: HTTPConnectionPool(host='148.66.155.177', port=444): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA580>, 'Connection to 148.66.155.177 timed out. (connect timeout=5)'))
A52 [原始行号:680] http://1.162.218.19:5001/v1/models -> Error: HTTPConnectionPool(host='1.162.218.19', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596C40>, 'Connection to 1.162.218.19 timed out. (connect timeout=5)'))
A53 [原始行号:49] http://85.214.132.98:3000/v1/models -> Error: 404 Client Error: Not Found for url: http://85.214.132.98:3000/v1/models
A54 [原始行号:286] http://114.43.216.162:5001/v1/models -> Error: HTTPConnectionPool(host='114.43.216.162', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35962B0>, 'Connection to 114.43.216.162 timed out. (connect timeout=5)'))
A55 [原始行号:168] http://208.109.246.221:444/v1/models -> Error: No host specified.
A56 [原始行号:220] http://84.166.21.86:5001/v1/models -> Error: HTTPConnectionPool(host='84.166.21.86', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0940>, 'Connection to 84.166.21.86 timed out. (connect timeout=5)'))
A57 [原始行号:618] http://91.33.98.84:9900/v1/models -> Error: HTTPConnectionPool(host='91.33.98.84', port=9900): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA910>, 'Connection to 91.33.98.84 timed out. (connect timeout=5)'))
A58 [原始行号:515] http://87.187.23.7:5001/v1/models -> Error: HTTPConnectionPool(host='87.187.23.7', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA3A0>, 'Connection to 87.187.23.7 timed out. (connect timeout=5)'))
A59 [原始行号:281] http://91.33.104.74:5001/v1/models -> Error: HTTPConnectionPool(host='91.33.104.74', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596F10>, 'Connection to 91.33.104.74 timed out. (connect timeout=5)'))
A60 [原始行号:404] http://91.8.81.31:5001/v1/models -> Error: HTTPConnectionPool(host='91.8.81.31', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D35860A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A61 [原始行号:582] http://219.140.142.207:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.142.207', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8E50>, 'Connection to 219.140.142.207 timed out. (connect timeout=5)'))
A62 [原始行号:30] http://122.160.15.158:1030/v1/models -> Error: 404 Client Error: Not Found for url: http://122.160.15.158:1030/v1/models
A63 [原始行号:360] http://219.140.143.148:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.143.148', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8F10>, 'Connection to 219.140.143.148 timed out. (connect timeout=5)'))
A64 [原始行号:33] http://195.201.16.238:8443/v1/models -> Error: 400 Client Error:  for url: http://195.201.16.238:8443/v1/models
A65 [原始行号:31] http://62.221.199.44:8443/v1/models -> Error: HTTPSConnectionPool(host='62.221.199.44', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '62.221.199.44' doesn't match either of '2is.nl', '*.2is.nl', '*.eatserver.nl'")))
A66 [原始行号:654] http://95.105.171.131:3000/v1/models -> Error: HTTPConnectionPool(host='95.105.171.131', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0820>, 'Connection to 95.105.171.131 timed out. (connect timeout=5)'))
A67 [原始行号:713] http://77.181.120.184:5001/v1/models -> Error: HTTPConnectionPool(host='77.181.120.184', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596760>, 'Connection to 77.181.120.184 timed out. (connect timeout=5)'))
A68 [原始行号:719] http://1.162.249.10:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.249.10', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596610>, 'Connection to 1.162.249.10 timed out. (connect timeout=5)'))
A69 [原始行号:608] http://77.181.1.136:5000/v1/models -> Error: HTTPConnectionPool(host='77.181.1.136', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DAA90>, 'Connection to 77.181.1.136 timed out. (connect timeout=5)'))
A70 [原始行号:411] http://84.105.53.168:5555/v1/models -> Error: HTTPConnectionPool(host='84.105.53.168', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA250>, 'Connection to 84.105.53.168 timed out. (connect timeout=5)'))
A71 [原始行号:741] http://77.187.21.163:5001/v1/models -> Error: HTTPConnectionPool(host='77.187.21.163', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35964F0>, 'Connection to 77.187.21.163 timed out. (connect timeout=5)'))
A72 [原始行号:446] http://91.193.131.35:1935/v1/models -> Error: HTTPConnectionPool(host='91.193.131.35', port=1935): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596790>, 'Connection to 91.193.131.35 timed out. (connect timeout=5)'))
A73 [原始行号:265] http://91.37.82.115:5001/v1/models -> Error: HTTPConnectionPool(host='91.37.82.115', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0AC0>, 'Connection to 91.37.82.115 timed out. (connect timeout=5)'))
A74 [原始行号:213] http://58.153.27.196:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://58.153.27.196:5000/v1/models
A75 [原始行号:324] http://46.13.171.220:8080/v1/models -> Error: HTTPConnectionPool(host='46.13.171.220', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586F70>, 'Connection to 46.13.171.220 timed out. (connect timeout=5)'))
A76 [原始行号:622] http://93.130.154.141:5001/v1/models -> Error: HTTPConnectionPool(host='93.130.154.141', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586C70>, 'Connection to 93.130.154.141 timed out. (connect timeout=5)'))
A77 [原始行号:590] http://144.91.109.139:7070/v1/models -> Error: HTTPConnectionPool(host='144.91.109.139', port=7070): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586BE0>, 'Connection to 144.91.109.139 timed out. (connect timeout=5)'))
A78 [原始行号:332] http://91.63.160.138:5001/v1/models -> Error: HTTPConnectionPool(host='91.63.160.138', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C88E0>, 'Connection to 91.63.160.138 timed out. (connect timeout=5)'))
A79 [原始行号:375] http://136.144.183.42:8880/v1/models -> Error: HTTPConnectionPool(host='136.144.183.42', port=8880): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0C70>, 'Connection to 136.144.183.42 timed out. (connect timeout=5)'))
A80 [原始行号:181] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A81 [原始行号:54] http://58.153.27.196:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://58.153.27.196:5001/v1/models
A82 [原始行号:733] http://1.162.205.95:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.205.95', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596970>, 'Connection to 1.162.205.95 timed out. (connect timeout=5)'))
A83 [原始行号:365] http://87.167.55.113:8888/v1/models -> Error: HTTPConnectionPool(host='87.167.55.113', port=8888): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA220>, 'Connection to 87.167.55.113 timed out. (connect timeout=5)'))
A84 [原始行号:97] http://82.194.205.68:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://82.194.205.68:5001/v1/models
A85 [原始行号:697] http://77.12.28.147:5001/v1/models -> Error: HTTPConnectionPool(host='77.12.28.147', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3349280>, 'Connection to 77.12.28.147 timed out. (connect timeout=5)'))
A86 [原始行号:579] http://1.162.234.251:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.234.251', port=5000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284B0D53040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A87 [原始行号:610] http://77.181.241.70:5000/v1/models -> Error: HTTPConnectionPool(host='77.181.241.70', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8820>, 'Connection to 77.181.241.70 timed out. (connect timeout=5)'))
A88 [原始行号:750] http://46.4.112.78:3000/v1/models -> Error: HTTPConnectionPool(host='46.4.112.78', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586DC0>, 'Connection to 46.4.112.78 timed out. (connect timeout=5)'))
A89 [原始行号:516] http://1.162.201.88:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.201.88', port=5000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D35860D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A90 [原始行号:350] http://87.187.26.105:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A91 [原始行号:120] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by ProxyError('Unable to connect to proxy', FileNotFoundError(2, 'No such file or directory')))
A92 [原始行号:780] http://198.12.253.170:444/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A93 [原始行号:84] http://211.10.90.212:8880/v1/models -> Error: 404 Client Error: Not Found for url: http://211.10.90.212:8880/v1/models
A94 [原始行号:10] http://91.107.211.61:3000/v1/models -> Error: 404 Client Error: Not Found for url: http://91.107.211.61:3000/v1/models
A95 [原始行号:512] http://1.162.201.88:5001/v1/models -> Error: 503 Server Error: Service Unavailable for url: http://1.162.201.88:5001/v1/models
A96 [原始行号:462] http://61.231.192.157:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.192.157', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8A60>, 'Connection to 61.231.192.157 timed out. (connect timeout=5)'))
A97 [原始行号:275] http://114.43.222.227:5000/v1/models -> Error: HTTPConnectionPool(host='114.43.222.227', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586700>, 'Connection to 114.43.222.227 timed out. (connect timeout=5)'))
A98 [原始行号:218] http://176.153.181.160:8201/v1/models -> Error: 400 Client Error: Bad Request for url: http://176.153.181.160:8201/v1/models
A99 [原始行号:344] http://87.167.58.14:8888/v1/models -> Error: HTTPConnectionPool(host='87.167.58.14', port=8888): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35868B0>, 'Connection to 87.167.58.14 timed out. (connect timeout=5)'))
A100 [原始行号:29] http://177.153.58.211:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://177.153.58.211:8080/v1/models
A101 [原始行号:772] http://61.231.209.4:5001/v1/models -> Error: HTTPConnectionPool(host='61.231.209.4', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586EE0>, 'Connection to 61.231.209.4 timed out. (connect timeout=5)'))
A102 [原始行号:457] http://219.140.150.103:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.150.103', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596D30>, 'Connection to 219.140.150.103 timed out. (connect timeout=5)'))
A103 [原始行号:65] http://103.245.22.246:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://103.245.22.246:8080/v1/models
A104 [原始行号:235] http://114.43.211.72:5000/v1/models -> Error: HTTPConnectionPool(host='114.43.211.72', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596280>, 'Connection to 114.43.211.72 timed out. (connect timeout=5)'))
A105 [原始行号:640] http://220.246.156.36:5000/v1/models -> Error: HTTPConnectionPool(host='220.246.156.36', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586CA0>, 'Connection to 220.246.156.36 timed out. (connect timeout=5)'))
A106 [原始行号:356] http://79.207.189.177:5001/v1/models -> Error: HTTPConnectionPool(host='79.207.189.177', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D3586BB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A107 [原始行号:81] http://209.122.132.208:8001/v1/models -> Error: 400 Client Error: Bad Request for url: http://209.122.132.208:8001/v1/models
A108 [原始行号:482] http://59.174.151.237:2000/v1/models -> Error: HTTPConnectionPool(host='59.174.151.237', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8370>, 'Connection to 59.174.151.237 timed out. (connect timeout=5)'))
A109 [原始行号:290] http://81.173.127.1:1443/v1/models -> Error: 400 Client Error: Bad Request for url: http://81.173.127.1:1443/v1/models
A110 [原始行号:643] http://79.207.178.56:5001/v1/models -> Error: HTTPConnectionPool(host='79.207.178.56', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8130>, 'Connection to 79.207.178.56 timed out. (connect timeout=5)'))
A111 [原始行号:558] http://45.33.94.182:3003/v1/models -> Error: HTTPConnectionPool(host='45.33.94.182', port=3003): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D3596EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A112 [原始行号:633] http://77.12.250.190:5000/v1/models -> Error: HTTPConnectionPool(host='77.12.250.190', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574430>, 'Connection to 77.12.250.190 timed out. (connect timeout=5)'))
A113 [原始行号:533] http://62.238.19.140:5001/v1/models -> Error: HTTPConnectionPool(host='62.238.19.140', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33ADAC0>, 'Connection to 62.238.19.140 timed out. (connect timeout=5)'))
A114 [原始行号:244] http://198.199.89.222:8081/v1/models -> Error: 404 Client Error: Not Found for url: http://198.199.89.222:8081/v1/models
A115 [原始行号:76] http://85.214.244.226:7081/v1/models -> Error: 400 Client Error: Bad Request for url: http://85.214.244.226:7081/v1/models
A116 [原始行号:260] http://45.87.137.49:8443/v1/models -> Error: HTTPSConnectionPool(host='45.87.137.49', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '45.87.137.49' doesn't match 'neun.jp-i.de'")))
A117 [原始行号:521] http://219.140.143.190:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.143.190', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35863A0>, 'Connection to 219.140.143.190 timed out. (connect timeout=5)'))
A118 [原始行号:495] http://77.172.153.14:8082/v1/models -> Error: 400 Client Error: Bad Request for url: http://77.172.153.14:8082/v1/models
A119 [原始行号:72] http://78.47.53.104:8000/v1/models ->   ✅ 成功：响应长度 81 字符
A120 [原始行号:672] http://1.162.197.155:5001/v1/models -> Error: HTTPConnectionPool(host='1.162.197.155', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA8B0>, 'Connection to 1.162.197.155 timed out. (connect timeout=5)'))
A121 [原始行号:432] http://84.19.30.183:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.183:1207/v1/models
A122 [原始行号:544] http://1.162.237.154:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.237.154', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA880>, 'Connection to 1.162.237.154 timed out. (connect timeout=5)'))
A123 [原始行号:703] http://1.162.199.18:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.199.18', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35861C0>, 'Connection to 1.162.199.18 timed out. (connect timeout=5)'))
A124 [原始行号:63] http://89.111.88.82:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://89.111.88.82:5000/v1/models
A125 [原始行号:465] http://91.51.215.7:5001/v1/models -> Error: HTTPConnectionPool(host='91.51.215.7', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35869A0>, 'Connection to 91.51.215.7 timed out. (connect timeout=5)'))
A126 [原始行号:670] http://101.71.237.0:5001/v1/models -> Error: HTTPConnectionPool(host='101.71.237.0', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33ADCD0>, 'Connection to 101.71.237.0 timed out. (connect timeout=5)'))
A127 [原始行号:744] http://88.159.35.242:5001/v1/models -> Error: HTTPConnectionPool(host='88.159.35.242', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596A60>, 'Connection to 88.159.35.242 timed out. (connect timeout=5)'))
A128 [原始行号:616] http://1.162.210.132:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.210.132', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0130>, 'Connection to 1.162.210.132 timed out. (connect timeout=5)'))
A129 [原始行号:247] http://37.120.182.4:8880/v1/models -> Error: 404 Client Error: Not Found for url: http://37.120.182.4:8880/v1/models
A130 [原始行号:442] http://84.19.30.231:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.231:1207/v1/models
A131 [原始行号:302] http://89.22.120.217:8443/v1/models -> Error: HTTPSConnectionPool(host='89.22.120.217', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '89.22.120.217' doesn't match 'vps48870.alfahosting-vps.de'")))
A132 [原始行号:362] http://31.15.10.143:84/v1/models -> Error: 404 Client Error: Not Found for url: http://31.15.10.143:84/v1/models
A133 [原始行号:683] http://175.0.105.136:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.105.136', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35863D0>, 'Connection to 175.0.105.136 timed out. (connect timeout=5)'))
A134 [原始行号:7] http://185.207.107.19:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://185.207.107.19:8080/v1/models
A135 [原始行号:300] http://46.36.40.127:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://46.36.40.127:8080/v1/models
A136 [原始行号:101] http://175.0.106.203:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.106.203', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586A60>, 'Connection to 175.0.106.203 timed out. (connect timeout=5)'))
A137 [原始行号:311] http://83.109.57.170:5000/v1/models -> Error: HTTPConnectionPool(host='83.109.57.170', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574970>, 'Connection to 83.109.57.170 timed out. (connect timeout=5)'))
A138 [原始行号:211] http://84.25.17.65:5001/v1/models -> Error: HTTPConnectionPool(host='84.25.17.65', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35B4490>, 'Connection to 84.25.17.65 timed out. (connect timeout=5)'))
A139 [原始行号:294] http://185.207.107.19:9443/v1/models -> Error: 400 Client Error: Bad Request for url: http://185.207.107.19:9443/v1/models
A140 [原始行号:2] http://219.140.142.216:2000/v1/models -> Error: 404 Client Error: Not Found for url: http://219.140.142.216:2000/v1/models
A141 [原始行号:707] http://61.231.198.176:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.198.176', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DAD00>, 'Connection to 61.231.198.176 timed out. (connect timeout=5)'))
A142 [原始行号:396] http://76.223.56.99:1935/v1/models -> Error: HTTPConnectionPool(host='76.223.56.99', port=1935): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586EB0>, 'Connection to 76.223.56.99 timed out. (connect timeout=5)'))
A143 [原始行号:380] http://34.232.251.42:8086/v1/models -> Error: HTTPConnectionPool(host='34.232.251.42', port=8086): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284B0D531C0>, 'Connection to 34.232.251.42 timed out. (connect timeout=5)'))
A144 [原始行号:507] http://1.162.204.26:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.204.26', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8C10>, 'Connection to 1.162.204.26 timed out. (connect timeout=5)'))
A145 [原始行号:675] http://45.33.94.182:4444/v1/models -> Error: HTTPConnectionPool(host='45.33.94.182', port=4444): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596070>, 'Connection to 45.33.94.182 timed out. (connect timeout=5)'))
A146 [原始行号:727] http://91.8.90.9:5001/v1/models -> Error: HTTPConnectionPool(host='91.8.90.9', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0C70>, 'Connection to 91.8.90.9 timed out. (connect timeout=5)'))
A147 [原始行号:490] http://91.56.72.56:5001/v1/models -> Error: HTTPConnectionPool(host='91.56.72.56', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8A60>, 'Connection to 91.56.72.56 timed out. (connect timeout=5)'))
A148 [原始行号:499] http://61.231.233.246:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.233.246', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284B0D53040>, 'Connection to 61.231.233.246 timed out. (connect timeout=5)'))
A149 [原始行号:259] http://202.61.225.250:8001/v1/models -> Error: 404 Client Error: Not Found for url: http://202.61.225.250:8001/v1/models
A150 [原始行号:424] http://84.19.30.123:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.123:1207/v1/models
A151 [原始行号:698] http://61.231.217.243:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.217.243', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35861F0>, 'Connection to 61.231.217.243 timed out. (connect timeout=5)'))
A152 [原始行号:352] http://1.162.237.64:5001/v1/models -> Error: HTTPConnectionPool(host='1.162.237.64', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574CA0>, 'Connection to 1.162.237.64 timed out. (connect timeout=5)'))
A153 [原始行号:79] http://13.202.97.97:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://13.202.97.97:8080/v1/models
A154 [原始行号:148] http://62.238.152.48:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://62.238.152.48:5001/v1/models
A155 [原始行号:334] http://61.231.196.97:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.196.97', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574550>, 'Connection to 61.231.196.97 timed out. (connect timeout=5)'))
A156 [原始行号:204] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A157 [原始行号:296] http://211.10.90.212:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.212', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.212' doesn't match 'www16.jan.ne.jp'")))
A158 [原始行号:602] http://61.231.205.151:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.205.151', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DAAC0>, 'Connection to 61.231.205.151 timed out. (connect timeout=5)'))
A159 [原始行号:133] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A160 [原始行号:239] http://114.43.211.72:5001/v1/models -> Error: HTTPConnectionPool(host='114.43.211.72', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596AF0>, 'Connection to 114.43.211.72 timed out. (connect timeout=5)'))
A161 [原始行号:55] http://93.232.161.154:8096/v1/models -> Error: HTTPConnectionPool(host='93.232.161.154', port=8096): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35B4CD0>, 'Connection to 93.232.161.154 timed out. (connect timeout=5)'))
A162 [原始行号:613] http://77.12.171.127:5001/v1/models -> Error: HTTPConnectionPool(host='77.12.171.127', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35AC6A0>, 'Connection to 77.12.171.127 timed out. (connect timeout=5)'))
A163 [原始行号:595] http://84.166.180.142:5001/v1/models -> Error: HTTPConnectionPool(host='84.166.180.142', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8FA0>, 'Connection to 84.166.180.142 timed out. (connect timeout=5)'))
A164 [原始行号:368] http://1.162.249.181:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.249.181', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA880>, 'Connection to 1.162.249.181 timed out. (connect timeout=5)'))
A165 [原始行号:543] http://88.88.132.154:5000/v1/models -> Error: HTTPConnectionPool(host='88.88.132.154', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35B4C40>, 'Connection to 88.88.132.154 timed out. (connect timeout=5)'))
A166 [原始行号:357] http://84.166.181.191:5001/v1/models -> Error: HTTPConnectionPool(host='84.166.181.191', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574E80>, 'Connection to 84.166.181.191 timed out. (connect timeout=5)'))
A167 [原始行号:591] http://61.231.246.5:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.246.5', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586C10>, 'Connection to 61.231.246.5 timed out. (connect timeout=5)'))
A168 [原始行号:501] http://84.166.28.223:9008/v1/models -> Error: HTTPConnectionPool(host='84.166.28.223', port=9008): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586910>, 'Connection to 84.166.28.223 timed out. (connect timeout=5)'))
A169 [原始行号:361] http://165.227.244.183:32769/v1/models -> Error: HTTPConnectionPool(host='165.227.244.183', port=32769): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D3574AC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A170 [原始行号:60] http://212.127.143.47:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://212.127.143.47:5000/v1/models
A171 [原始行号:724] http://175.0.105.211:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.105.211', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D35B4A00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A172 [原始行号:456] http://1.162.216.50:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.216.50', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8880>, 'Connection to 1.162.216.50 timed out. (connect timeout=5)'))
A173 [原始行号:439] http://84.19.30.241:1207/v1/models -> Error: HTTPConnectionPool(host='84.19.30.241', port=1207): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596640>, 'Connection to 84.19.30.241 timed out. (connect timeout=5)'))
A174 [原始行号:651] http://175.0.105.97:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.105.97', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586C40>, 'Connection to 175.0.105.97 timed out. (connect timeout=5)'))
A175 [原始行号:425] http://84.19.30.186:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.186:1207/v1/models
A176 [原始行号:443] http://84.19.30.246:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.246:1207/v1/models
A177 [原始行号:377] http://217.121.20.62:8877/v1/models -> Error: HTTPConnectionPool(host='217.121.20.62', port=8877): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8760>, 'Connection to 217.121.20.62 timed out. (connect timeout=5)'))
A178 [原始行号:264] http://45.142.17.195:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://45.142.17.195:5000/v1/models
A179 [原始行号:523] http://217.251.65.81:5001/v1/models -> Error: HTTPConnectionPool(host='217.251.65.81', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8910>, 'Connection to 217.251.65.81 timed out. (connect timeout=5)'))
A180 [原始行号:90] http://211.10.90.206:8880/v1/models -> Error: 404 Client Error: Not Found for url: http://211.10.90.206:8880/v1/models
A181 [原始行号:398] http://62.210.124.126:8086/v1/models -> Error: HTTPConnectionPool(host='62.210.124.126', port=8086): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DABB0>, 'Connection to 62.210.124.126 timed out. (connect timeout=5)'))
A182 [原始行号:522] http://84.166.187.236:5001/v1/models -> Error: HTTPConnectionPool(host='84.166.187.236', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35B4B20>, 'Connection to 84.166.187.236 timed out. (connect timeout=5)'))
A183 [原始行号:762] http://84.130.209.8:8443/v1/models -> Error: HTTPConnectionPool(host='84.130.209.8', port=8443): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35748E0>, 'Connection to 84.130.209.8 timed out. (connect timeout=5)'))
A184 [原始行号:158] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A185 [原始行号:69] http://178.118.149.97:5000/v1/models -> Error: 404 Client Error: Not Found for url: http://178.118.149.97:5000/v1/models
A186 [原始行号:485] http://91.56.71.101:5001/v1/models -> Error: HTTPConnectionPool(host='91.56.71.101', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574760>, 'Connection to 91.56.71.101 timed out. (connect timeout=5)'))
A187 [原始行号:131] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A188 [原始行号:44] http://206.251.162.126:9901/v1/models -> Error: 400 Client Error: Bad Request for url: http://206.251.162.126:9901/v1/models
A189 [原始行号:70] http://65.108.128.58:9000/v1/models ->   ✅ 成功：响应长度 83 字符
A190 [原始行号:209] http://89.111.88.82:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://89.111.88.82:5001/v1/models
A191 [原始行号:627] http://34.89.21.165:3000/v1/models -> Error: HTTPConnectionPool(host='34.89.21.165', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35745E0>, 'Connection to 34.89.21.165 timed out. (connect timeout=5)'))
A192 [原始行号:299] http://59.173.29.249:2000/v1/models -> Error: HTTPConnectionPool(host='59.173.29.249', port=2000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D3349880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A193 [原始行号:625] http://79.207.178.56:8801/v1/models -> Error: HTTPConnectionPool(host='79.207.178.56', port=8801): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586F40>, 'Connection to 79.207.178.56 timed out. (connect timeout=5)'))
A194 [原始行号:135] http://198.199.89.222:8081/v1/models -> Error: 404 Client Error: Not Found for url: http://198.199.89.222:8081/v1/models
A195 [原始行号:635] http://77.12.250.190:5001/v1/models -> Error: HTTPConnectionPool(host='77.12.250.190', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574AC0>, 'Connection to 77.12.250.190 timed out. (connect timeout=5)'))
A196 [原始行号:165] http://87.195.147.161:4000/v1/models -> Error: 404 Client Error: Not Found for url: http://87.195.147.161:4000/v1/models
A197 [原始行号:164] http://13.126.75.14:8080/v1/models -> Error: HTTPConnectionPool(host='13.126.75.14', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8B20>, 'Connection to 13.126.75.14 timed out. (connect timeout=5)'))
A198 [原始行号:28] http://213.119.177.104:8888/v1/models -> Error: 404 Client Error: Not found for url: http://213.119.177.104:8888/v1/models
A199 [原始行号:428] http://84.19.30.242:1207/v1/models -> Error: HTTPConnectionPool(host='84.19.30.242', port=1207): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8B50>, 'Connection to 84.19.30.242 timed out. (connect timeout=5)'))
A200 [原始行号:193] http://43.252.89.90:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://43.252.89.90:8080/v1/models
A201 [原始行号:336] http://61.231.196.97:5001/v1/models -> Error: HTTPConnectionPool(host='61.231.196.97', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596FA0>, 'Connection to 61.231.196.97 timed out. (connect timeout=5)'))
A202 [原始行号:506] http://1.162.204.26:5001/v1/models -> Error: HTTPConnectionPool(host='1.162.204.26', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586D30>, 'Connection to 1.162.204.26 timed out. (connect timeout=5)'))
A203 [原始行号:433] http://84.19.30.243:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.243:1207/v1/models
A204 [原始行号:136] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A205 [原始行号:537] http://59.173.28.69:2000/v1/models -> Error: HTTPConnectionPool(host='59.173.28.69', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8BE0>, 'Connection to 59.173.28.69 timed out. (connect timeout=5)'))
A206 [原始行号:603] http://91.58.42.145:5001/v1/models -> Error: HTTPConnectionPool(host='91.58.42.145', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284B0D530D0>, 'Connection to 91.58.42.145 timed out. (connect timeout=5)'))
A207 [原始行号:140] http://84.166.30.230:5001/v1/models -> Error: HTTPConnectionPool(host='84.166.30.230', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574E20>, 'Connection to 84.166.30.230 timed out. (connect timeout=5)'))
A208 [原始行号:774] http://175.0.106.146:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.106.146', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D2FB8B20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A209 [原始行号:6] http://153.127.46.133:8880/v1/models -> Error: HTTPConnectionPool(host='153.127.46.133', port=8880): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586670>, 'Connection to 153.127.46.133 timed out. (connect timeout=5)'))
A210 [原始行号:483] http://109.133.66.104:8850/v1/models ->   ✅ 成功：响应长度 263 字符
A211 [原始行号:467] http://219.140.151.65:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.151.65', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35866D0>, 'Connection to 219.140.151.65 timed out. (connect timeout=5)'))
A212 [原始行号:73] http://85.248.25.132:85/v1/models -> Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
A213 [原始行号:604] http://59.174.151.89:2000/v1/models -> Error: HTTPConnectionPool(host='59.174.151.89', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D337FF40>, 'Connection to 59.174.151.89 timed out. (connect timeout=5)'))
A214 [原始行号:250] http://81.173.226.74:6543/v1/models -> Error: HTTPConnectionPool(host='81.173.226.74', port=6543): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35961F0>, 'Connection to 81.173.226.74 timed out. (connect timeout=5)'))
A215 [原始行号:145] http://114.43.227.225:5001/v1/models -> Error: HTTPConnectionPool(host='114.43.227.225', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35967F0>, 'Connection to 114.43.227.225 timed out. (connect timeout=5)'))
A216 [原始行号:658] http://61.231.242.195:5001/v1/models -> Error: HTTPConnectionPool(host='61.231.242.195', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA8E0>, 'Connection to 61.231.242.195 timed out. (connect timeout=5)'))
A217 [原始行号:319] http://84.166.188.31:5001/v1/models -> Error: HTTPConnectionPool(host='84.166.188.31', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35961F0>, 'Connection to 84.166.188.31 timed out. (connect timeout=5)'))
A218 [原始行号:706] http://159.203.44.54:9801/v1/models -> Error: HTTPConnectionPool(host='159.203.44.54', port=9801): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D32E0AF0>, 'Connection to 159.203.44.54 timed out. (connect timeout=5)'))
A219 [原始行号:132] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A220 [原始行号:615] http://219.140.150.131:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.150.131', port=2000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D35863D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A221 [原始行号:420] http://175.0.133.83:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.133.83', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35868E0>, 'Connection to 175.0.133.83 timed out. (connect timeout=5)'))
A222 [原始行号:732] http://77.187.151.129:5000/v1/models -> Error: HTTPConnectionPool(host='77.187.151.129', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35862E0>, 'Connection to 77.187.151.129 timed out. (connect timeout=5)'))
A223 [原始行号:409] http://34.232.251.42:1935/v1/models -> Error: HTTPConnectionPool(host='34.232.251.42', port=1935): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586790>, 'Connection to 34.232.251.42 timed out. (connect timeout=5)'))
A224 [原始行号:41] http://82.72.198.40:5555/v1/models -> Error: 404 Client Error: Not Found for url: http://82.72.198.40:5555/v1/models
A225 [原始行号:748] http://1.162.214.102:5001/v1/models -> Error: HTTPConnectionPool(host='1.162.214.102', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574C40>, 'Connection to 1.162.214.102 timed out. (connect timeout=5)'))
A226 [原始行号:108] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A227 [原始行号:329] http://40.115.59.215:9195/v1/models -> Error: HTTPConnectionPool(host='40.115.59.215', port=9195): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35961C0>, 'Connection to 40.115.59.215 timed out. (connect timeout=5)'))
A228 [原始行号:56] http://188.91.14.22:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://188.91.14.22:5001/v1/models
A229 [原始行号:734] http://2.201.223.60:5000/v1/models -> Error: HTTPConnectionPool(host='2.201.223.60', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35969A0>, 'Connection to 2.201.223.60 timed out. (connect timeout=5)'))
A230 [原始行号:673] http://77.181.128.242:5000/v1/models -> Error: HTTPConnectionPool(host='77.181.128.242', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D35968B0>, 'Connection to 77.181.128.242 timed out. (connect timeout=5)'))
A231 [原始行号:393] http://1.162.230.96:5001/v1/models -> Error: HTTPConnectionPool(host='1.162.230.96', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0460>, 'Connection to 1.162.230.96 timed out. (connect timeout=5)'))
A232 [原始行号:227] http://59.174.151.105:2000/v1/models -> Error: HTTPConnectionPool(host='59.174.151.105', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33C8AC0>, 'Connection to 59.174.151.105 timed out. (connect timeout=5)'))
A233 [原始行号:212] http://88.159.10.216:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://88.159.10.216:5001/v1/models
A234 [原始行号:581] http://87.197.107.246:444/v1/models -> Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
A235 [原始行号:538] http://91.33.111.181:5001/v1/models -> Error: HTTPConnectionPool(host='91.33.111.181', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DA7F0>, 'Connection to 91.33.111.181 timed out. (connect timeout=5)'))
A236 [原始行号:24] http://87.187.20.236:5001/v1/models -> Error: 400 Client Error: Bad Request for url: http://87.187.20.236:5001/v1/models
A237 [原始行号:254] http://114.43.208.90:5000/v1/models -> Error: HTTPConnectionPool(host='114.43.208.90', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574C10>, 'Connection to 114.43.208.90 timed out. (connect timeout=5)'))
A238 [原始行号:445] http://84.19.30.245:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.245:1207/v1/models
A239 [原始行号:335] http://79.207.185.119:5001/v1/models -> Error: HTTPConnectionPool(host='79.207.185.119', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33DAC70>, 'Connection to 79.207.185.119 timed out. (connect timeout=5)'))
A240 [原始行号:598] http://77.189.108.72:5000/v1/models -> Error: HTTPConnectionPool(host='77.189.108.72', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D33B0D90>, 'Connection to 77.189.108.72 timed out. (connect timeout=5)'))
A241 [原始行号:340] http://213.239.215.98:8840/v1/models -> Error: 404 Client Error: Not Found for url: http://213.239.215.98:8840/v1/models
A242 [原始行号:110] http://211.10.90.206:8443/v1/models -> Error: HTTPSConnectionPool(host='211.10.90.206', port=8443): Max retries exceeded with url: /v1/models (Caused by SSLError(CertificateError("hostname '211.10.90.206' doesn't match 'www15.jan.ne.jp'")))
A243 [原始行号:82] http://81.164.186.143:8092/v1/models -> Error: 404 Client Error: Not Found for url: http://81.164.186.143:8092/v1/models
A244 [原始行号:51] http://94.145.227.35:3000/v1/models -> Error: HTTPConnectionPool(host='94.145.227.35', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574BB0>, 'Connection to 94.145.227.35 timed out. (connect timeout=5)'))
A245 [原始行号:570] http://87.187.19.188:5001/v1/models -> Error: HTTPConnectionPool(host='87.187.19.188', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586790>, 'Connection to 87.187.19.188 timed out. (connect timeout=5)'))
A246 [原始行号:363] http://206.189.114.107:8001/v1/models -> Error: HTTPConnectionPool(host='206.189.114.107', port=8001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D35966A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A247 [原始行号:716] http://219.140.142.25:2000/v1/models -> Error: HTTPConnectionPool(host='219.140.142.25', port=2000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574400>, 'Connection to 219.140.142.25 timed out. (connect timeout=5)'))
A248 [原始行号:630] http://93.130.251.184:5001/v1/models -> Error: HTTPConnectionPool(host='93.130.251.184', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284B0D42FD0>, 'Connection to 93.130.251.184 timed out. (connect timeout=5)'))
A249 [原始行号:198] http://217.154.67.130:8083/v1/models ->   ✅ 成功：响应长度 263 字符
A250 [原始行号:547] http://175.0.101.154:5001/v1/models -> Error: HTTPConnectionPool(host='175.0.101.154', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000284D33DA040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A251 [原始行号:342] http://44.205.5.241:8080/v1/models -> Error: HTTPConnectionPool(host='44.205.5.241', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586670>, 'Connection to 44.205.5.241 timed out. (connect timeout=5)'))
A252 [原始行号:429] http://84.19.30.239:1207/v1/models -> Error: 404 Client Error: Not Found for url: http://84.19.30.239:1207/v1/models
A253 [原始行号:479] http://1.162.216.126:5000/v1/models -> Error: HTTPConnectionPool(host='1.162.216.126', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284B0D42FD0>, 'Connection to 1.162.216.126 timed out. (connect timeout=5)'))
A254 [原始行号:624] http://61.231.197.3:5000/v1/models -> Error: HTTPConnectionPool(host='61.231.197.3', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574040>, 'Connection to 61.231.197.3 timed out. (connect timeout=5)'))
A255 [原始行号:139] http://94.145.232.208:3000/v1/models -> Error: HTTPConnectionPool(host='94.145.232.208', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3574850>, 'Connection to 94.145.232.208 timed out. (connect timeout=5)'))
A256 [原始行号:423] http://209.205.150.30:81/v1/models -> Error: HTTPConnectionPool(host='209.205.150.30', port=81): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3586820>, 'Connection to 209.205.150.30 timed out. (connect timeout=5)'))
A257 [原始行号:731] http://91.44.159.19:5001/v1/models -> Error: HTTPConnectionPool(host='91.44.159.19', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x00000284D3596DF0>, 'Connection to 91.44.159.19 timed out. (connect timeout=5)'))
A258 [原始行号:18] http://109.183.237.220:11000/v1/models -> Error: 404 Client Error: File not found for url: http://109.183.237.220:11000/v1/models
