http://115.127.224.131:8080/v1/models | Error: HTTPConnectionPool(host='115.127.224.131', port=8080): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EAD9820>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://77.237.247.187:8080/v1/files | Status: 404 | Response: File Not Found
http://98.188.101.102:8080/v1/models | Status: 404 | Response: <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewp
http://98.85.58.138:8080/v1/files | Status: 404 | Response: File Not Found
http://176.10.127.176:8080/v1/models | Status: 200 | Response: {"data":[{"created":1745392936,"id":"google_gemma-3-1b-it-Q6_K.gguf","object":"model","owned_by":"ll
http://20.235.41.63:8080/v1/files | Status: 404 | Response: File Not Found
http://129.159.132.119:8080/v1/models | Status: 200 | Response: {"data":[{"created":1745392937,"id":"qwen2.5-1.5b-instruct-q6_k.gguf","object":"model","owned_by":"l
http://65.109.97.121:8080/v1/files | Error: HTTPConnectionPool(host='65.109.97.121', port=8080): Max retries exceeded with url: /v1/files (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EC53220>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://20.38.44.226:8080/v1/models | Error: HTTPConnectionPool(host='20.38.44.226', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC64610>, 'Connection to 20.38.44.226 timed out. (connect timeout=10)'))
http://144.24.13.192:8080/v1/files | Error: HTTPConnectionPool(host='144.24.13.192', port=8080): Read timed out. (read timeout=10)
http://43.201.96.66:8080/v1/models | Error: HTTPConnectionPool(host='43.201.96.66', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EB6ACA0>, 'Connection to 43.201.96.66 timed out. (connect timeout=10)'))
http://185.44.211.57:8080/v1/files | Error: HTTPConnectionPool(host='185.44.211.57', port=8080): Max retries exceeded with url: /v1/files (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EC645B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://45.45.217.219:8080/v1/models | Error: HTTPConnectionPool(host='45.45.217.219', port=8080): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EC64FA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://20.193.140.56:8080/v1/files | Error: HTTPConnectionPool(host='20.193.140.56', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC67940>, 'Connection to 20.193.140.56 timed out. (connect timeout=10)'))
http://116.203.144.88:8080/v1/models | Error: HTTPConnectionPool(host='116.203.144.88', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6B2B0>, 'Connection to 116.203.144.88 timed out. (connect timeout=10)'))
http://45.56.103.188:8080/v1/files | Error: HTTPConnectionPool(host='45.56.103.188', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EAD9820>, 'Connection to 45.56.103.188 timed out. (connect timeout=10)'))
http://140.116.82.100:8080/v1/models | Error: HTTPConnectionPool(host='140.116.82.100', port=8080): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EB53280>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://84.247.136.227:8080/v1/files | Error: HTTPConnectionPool(host='84.247.136.227', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC53F70>, 'Connection to 84.247.136.227 timed out. (connect timeout=10)'))
http://188.251.163.19:8080/v1/models | Error: HTTPConnectionPool(host='188.251.163.19', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6B880>, 'Connection to 188.251.163.19 timed out. (connect timeout=10)'))
http://34.66.191.209:8080/v1/files | Error: HTTPConnectionPool(host='34.66.191.209', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6C1F0>, 'Connection to 34.66.191.209 timed out. (connect timeout=10)'))
http://149.165.174.161:8080/v1/models | Error: HTTPConnectionPool(host='149.165.174.161', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6CB20>, 'Connection to 149.165.174.161 timed out. (connect timeout=10)'))
http://34.107.111.188:8080/v1/files | Error: HTTPConnectionPool(host='34.107.111.188', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EB6A970>, 'Connection to 34.107.111.188 timed out. (connect timeout=10)'))
http://35.198.75.16:8080/v1/models | Error: HTTPConnectionPool(host='35.198.75.16', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6BE20>, 'Connection to 35.198.75.16 timed out. (connect timeout=10)'))
http://3.110.146.237:8080/v1/files | Error: HTTPConnectionPool(host='3.110.146.237', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6B2E0>, 'Connection to 3.110.146.237 timed out. (connect timeout=10)'))
http://34.173.15.184:8080/v1/models | Error: HTTPConnectionPool(host='34.173.15.184', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EB53730>, 'Connection to 34.173.15.184 timed out. (connect timeout=10)'))
http://101.201.63.11:8080/v1/files | Error: HTTPConnectionPool(host='101.201.63.11', port=8080): Max retries exceeded with url: /v1/files (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EB58580>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://78.47.132.195:8080/v1/models | Error: HTTPConnectionPool(host='78.47.132.195', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6CBB0>, 'Connection to 78.47.132.195 timed out. (connect timeout=10)'))
http://157.245.100.133:8080/v1/files | Error: HTTPConnectionPool(host='157.245.100.133', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EB58C10>, 'Connection to 157.245.100.133 timed out. (connect timeout=10)'))
http://146.190.10.199:8080/v1/models | Error: HTTPConnectionPool(host='146.190.10.199', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EB53130>, 'Connection to 146.190.10.199 timed out. (connect timeout=10)'))
http://152.42.156.79:8080/v1/files | Error: HTTPConnectionPool(host='152.42.156.79', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6B670>, 'Connection to 152.42.156.79 timed out. (connect timeout=10)'))
http://139.59.26.88:8080/v1/models | Error: HTTPConnectionPool(host='139.59.26.88', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A73C4C2EE0>, 'Connection to 139.59.26.88 timed out. (connect timeout=10)'))
http://152.42.156.5:8080/v1/files | Error: HTTPConnectionPool(host='152.42.156.5', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC536A0>, 'Connection to 152.42.156.5 timed out. (connect timeout=10)'))
http://77.125.67.19:8080/v1/models | Error: HTTPConnectionPool(host='77.125.67.19', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6C130>, 'Connection to 77.125.67.19 timed out. (connect timeout=10)'))
http://52.184.197.226:8080/v1/files | Error: HTTPConnectionPool(host='52.184.197.226', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC53520>, 'Connection to 52.184.197.226 timed out. (connect timeout=10)'))
http://114.55.224.226:8080/v1/models | Error: HTTPConnectionPool(host='114.55.224.226', port=8080): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EC6B9D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://147.102.11.59:8080/v1/files | Error: HTTPConnectionPool(host='147.102.11.59', port=8080): Max retries exceeded with url: /v1/files (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6B790>, 'Connection to 147.102.11.59 timed out. (connect timeout=10)'))
http://86.42.2.80:8080/v1/models | Error: HTTPConnectionPool(host='86.42.2.80', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EB535B0>, 'Connection to 86.42.2.80 timed out. (connect timeout=10)'))
http://91.237.249.25:8080/v1/files | Error: HTTPConnectionPool(host='91.237.249.25', port=8080): Max retries exceeded with url: /v1/files (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A75EB58AC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
http://185.18.212.190:8080/v1/models | Error: HTTPConnectionPool(host='185.18.212.190', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002A75EC6CC40>, 'Connection to 185.18.212.190 timed out. (connect timeout=10)'))
