A1 [原始行号:703] http://174.79.3.247:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A2 [原始行号:33] http://98.111.193.159:5001/v1/models ->   ✅ 成功：响应长度 89 字符
A3 [原始行号:300] http://158.69.121.172:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A4 [原始行号:456] http://46.0.139.10:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A5 [原始行号:633] http://18.236.227.131:8000/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A6 [原始行号:557] http://95.53.169.99:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A7 [原始行号:39] http://45.178.149.96:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A8 [原始行号:356] http://45.47.159.106:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A9 [原始行号:559] http://144.76.201.184:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A10 [原始行号:514] http://108.20.142.112:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A11 [原始行号:729] http://83.200.134.82:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A12 [原始行号:355] http://5.164.166.81:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A13 [原始行号:164] http://99.114.163.206:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A14 [原始行号:697] http://31.180.165.148:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A15 [原始行号:66] http://161.97.182.94:5001/v1/models -> Error: 503 Server Error: Service Unavailable for url: http://161.97.182.94:5001/v1/models
A16 [原始行号:78] http://51.162.33.30:8008/v1/models -> Error: 503 Server Error: Service Unavailable for url: http://51.162.33.30:8008/v1/models
A17 [原始行号:72] http://188.25.208.165:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A18 [原始行号:643] http://218.149.40.161:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A19 [原始行号:181] http://86.2.8.125:3000/v1/models -> Error: 503 Server Error: Service Unavailable for url: http://86.2.8.125:3000/v1/models
A20 [原始行号:380] http://218.32.95.139:8010/v1/models -> Error: 500 Server Error: Internal Server Error for url: http://218.32.95.139:8010/v1/models
A21 [原始行号:606] http://150.136.70.19:9090/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A22 [原始行号:545] http://193.122.153.102:9090/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A23 [原始行号:467] http://88.112.164.141:5001/v1/models -> Error: 503 Server Error: Service Unavailable for url: http://88.112.164.141:5001/v1/models
A24 [原始行号:65] http://86.216.219.31:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A25 [原始行号:54] http://86.131.160.166:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A26 [原始行号:235] http://125.229.155.140:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A27 [原始行号:81] http://74.48.194.238:8090/v1/models -> Error: 404 Client Error:  for url: http://74.48.194.238:8090/v1/models
A28 [原始行号:632] http://68.50.29.53:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A29 [原始行号:404] http://47.116.106.28:25565/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A30 [原始行号:717] http://50.159.149.52:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A31 [原始行号:344] http://71.33.139.207:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A32 [原始行号:286] http://111.248.227.98:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A33 [原始行号:480] http://89.109.4.88:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A34 [原始行号:523] http://108.85.175.59:5001/v1/models -> Error: HTTPConnectionPool(host='127.0.0.1', port=10808): Read timed out. (read timeout=5)
A35 [原始行号:465] http://67.213.221.10:5001/v1/models -> Error: HTTPConnectionPool(host='67.213.221.10', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A5E0>, 'Connection to 67.213.221.10 timed out. (connect timeout=5)'))
A36 [原始行号:448] http://125.66.97.99:5555/v1/models -> Error: HTTPConnectionPool(host='125.66.97.99', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EE370>, 'Connection to 125.66.97.99 timed out. (connect timeout=5)'))
A37 [原始行号:601] http://5.164.177.154:5001/v1/models -> Error: HTTPConnectionPool(host='5.164.177.154', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8520>, 'Connection to 5.164.177.154 timed out. (connect timeout=5)'))
A38 [原始行号:602] http://125.229.140.92:5001/v1/models -> Error: HTTPConnectionPool(host='125.229.140.92', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E799CEE0>, 'Connection to 125.229.140.92 timed out. (connect timeout=5)'))
A39 [原始行号:326] http://119.177.53.13:8444/v1/models -> Error: HTTPConnectionPool(host='119.177.53.13', port=8444): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3D90>, 'Connection to 119.177.53.13 timed out. (connect timeout=5)'))
A40 [原始行号:10] http://129.213.19.7:9090/v1/models -> Error: 401 Client Error: Unauthorized for url: http://129.213.19.7:9090/v1/models
A41 [原始行号:109] http://188.245.200.15:8322/v1/models -> Error: 404 Client Error: Not Found for url: http://188.245.200.15:8322/v1/models
A42 [原始行号:430] http://47.99.46.11:8080/v1/models -> Error: HTTPConnectionPool(host='47.99.46.11', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0DF0>, 'Connection to 47.99.46.11 timed out. (connect timeout=5)'))
A43 [原始行号:578] http://46.33.34.233:5001/v1/models -> Error: HTTPConnectionPool(host='46.33.34.233', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7779280>, 'Connection to 46.33.34.233 timed out. (connect timeout=5)'))
A44 [原始行号:155] http://73.111.179.106:5001/v1/models -> Error: HTTPConnectionPool(host='73.111.179.106', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8370>, 'Connection to 73.111.179.106 timed out. (connect timeout=5)'))
A45 [原始行号:569] http://125.66.87.165:5555/v1/models -> Error: HTTPConnectionPool(host='125.66.87.165', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EE3A0>, 'Connection to 125.66.87.165 timed out. (connect timeout=5)'))
A46 [原始行号:340] http://96.53.168.35:5001/v1/models -> Error: HTTPConnectionPool(host='96.53.168.35', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3400>, 'Connection to 96.53.168.35 timed out. (connect timeout=5)'))
A47 [原始行号:198] http://150.136.38.97:9090/v1/models -> Error: HTTPConnectionPool(host='150.136.38.97', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780AF70>, 'Connection to 150.136.38.97 timed out. (connect timeout=5)'))
A48 [原始行号:436] http://220.189.110.102:5001/v1/models -> Error: HTTPConnectionPool(host='220.189.110.102', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E780A970>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A49 [原始行号:513] http://74.249.8.21:5000/v1/models -> Error: HTTPConnectionPool(host='74.249.8.21', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A50A0>, 'Connection to 74.249.8.21 timed out. (connect timeout=5)'))
A50 [原始行号:449] http://125.66.80.25:5555/v1/models -> Error: HTTPConnectionPool(host='125.66.80.25', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A550>, 'Connection to 125.66.80.25 timed out. (connect timeout=5)'))
A51 [原始行号:247] http://47.238.109.254:8081/v1/models -> Error: HTTPConnectionPool(host='47.238.109.254', port=8081): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77F80D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A52 [原始行号:351] http://194.163.171.40:5001/v1/models -> Error: HTTPConnectionPool(host='194.163.171.40', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A30A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A53 [原始行号:357] http://5.39.220.214:5001/v1/models -> Error: HTTPConnectionPool(host='5.39.220.214', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3F10>, 'Connection to 5.39.220.214 timed out. (connect timeout=5)'))
A54 [原始行号:210] http://68.103.117.96:5001/v1/models -> Error: HTTPConnectionPool(host='68.103.117.96', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E73E8A30>, 'Connection to 68.103.117.96 timed out. (connect timeout=5)'))
A55 [原始行号:227] http://124.222.66.24:9997/v1/models -> Error: HTTPConnectionPool(host='124.222.66.24', port=9997): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7779880>, 'Connection to 124.222.66.24 timed out. (connect timeout=5)'))
A56 [原始行号:244] http://95.72.111.17:81/v1/models -> Error: HTTPConnectionPool(host='95.72.111.17', port=81): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77EE550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A57 [原始行号:265] http://91.66.126.64:5001/v1/models -> Error: HTTPConnectionPool(host='91.66.126.64', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3C70>, 'Connection to 91.66.126.64 timed out. (connect timeout=5)'))
A58 [原始行号:120] http://61.43.98.20:5001/v1/models ->   ✅ 成功：响应长度 259 字符
A59 [原始行号:148] http://158.180.87.209:3000/v1/models -> Error: HTTPConnectionPool(host='158.180.87.209', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3790>, 'Connection to 158.180.87.209 timed out. (connect timeout=5)'))
A60 [原始行号:580] http://34.91.81.251:1234/v1/models -> Error: HTTPConnectionPool(host='34.91.81.251', port=1234): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A4C0>, 'Connection to 34.91.81.251 timed out. (connect timeout=5)'))
A61 [原始行号:443] http://34.172.254.134:5001/v1/models -> Error: HTTPConnectionPool(host='34.172.254.134', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0430>, 'Connection to 34.172.254.134 timed out. (connect timeout=5)'))
A62 [原始行号:542] http://216.121.169.79:5001/v1/models -> Error: HTTPConnectionPool(host='216.121.169.79', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0760>, 'Connection to 216.121.169.79 timed out. (connect timeout=5)'))
A63 [原始行号:97] http://139.196.89.237:5001/v1/models -> Error: HTTPConnectionPool(host='139.196.89.237', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0040>, 'Connection to 139.196.89.237 timed out. (connect timeout=5)'))
A64 [原始行号:595] http://73.35.201.59:5001/v1/models -> Error: HTTPConnectionPool(host='73.35.201.59', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A760>, 'Connection to 73.35.201.59 timed out. (connect timeout=5)'))
A65 [原始行号:597] http://183.252.181.153:5001/v1/models -> Error: HTTPConnectionPool(host='183.252.181.153', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77DDDC0>, 'Connection to 183.252.181.153 timed out. (connect timeout=5)'))
A66 [原始行号:536] http://67.140.157.116:10002/v1/models -> Error: HTTPConnectionPool(host='67.140.157.116', port=10002): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F81C0>, 'Connection to 67.140.157.116 timed out. (connect timeout=5)'))
A67 [原始行号:550] http://47.189.172.166:5001/v1/models -> Error: HTTPConnectionPool(host='47.189.172.166', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3CA0>, 'Connection to 47.189.172.166 timed out. (connect timeout=5)'))
A68 [原始行号:211] http://213.141.140.52:5001/v1/models -> Error: HTTPConnectionPool(host='213.141.140.52', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A56A0>, 'Connection to 213.141.140.52 timed out. (connect timeout=5)'))
A69 [原始行号:63] http://92.34.0.144:5001/v1/models ->   ✅ 成功：响应长度 263 字符
A70 [原始行号:624] http://35.90.205.129:8000/v1/models -> Error: HTTPConnectionPool(host='35.90.205.129', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3430>, 'Connection to 35.90.205.129 timed out. (connect timeout=5)'))
A71 [原始行号:77] http://158.101.121.194:9090/v1/models -> Error: 401 Client Error: Unauthorized for url: http://158.101.121.194:9090/v1/models
A72 [原始行号:49] http://76.134.32.52:5001/v1/models ->   ✅ 成功：响应长度 84 字符
A73 [原始行号:338] http://68.169.145.113:5001/v1/models -> Error: HTTPConnectionPool(host='68.169.145.113', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A0160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A74 [原始行号:118] http://68.58.150.54:5001/v1/models -> Error: HTTPConnectionPool(host='68.58.150.54', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780AA30>, 'Connection to 68.58.150.54 timed out. (connect timeout=5)'))
A75 [原始行号:423] http://113.205.131.202:5001/v1/models -> Error: HTTPConnectionPool(host='113.205.131.202', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A3A0>, 'Connection to 113.205.131.202 timed out. (connect timeout=5)'))
A76 [原始行号:101] http://167.88.3.210:5001/v1/models -> Error: HTTPConnectionPool(host='167.88.3.210', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A03D0>, 'Connection to 167.88.3.210 timed out. (connect timeout=5)'))
A77 [原始行号:675] http://129.213.23.152:9090/v1/models -> Error: HTTPConnectionPool(host='129.213.23.152', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3A30>, 'Connection to 129.213.23.152 timed out. (connect timeout=5)'))
A78 [原始行号:290] http://37.187.76.13:10086/v1/models -> Error: HTTPConnectionPool(host='37.187.76.13', port=10086): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E780A0D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A79 [原始行号:23] http://94.60.136.241:5001/v1/models ->   ✅ 成功：响应长度 274 字符
A80 [原始行号:158] http://46.173.226.133:5001/v1/models -> Error: HTTPConnectionPool(host='46.173.226.133', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A37F0>, 'Connection to 46.173.226.133 timed out. (connect timeout=5)'))
A81 [原始行号:726] http://183.143.169.206:5001/v1/models -> Error: HTTPConnectionPool(host='183.143.169.206', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77F8E20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A82 [原始行号:86] http://178.69.215.108:5001/v1/models -> Error: HTTPConnectionPool(host='178.69.215.108', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8520>, 'Connection to 178.69.215.108 timed out. (connect timeout=5)'))
A83 [原始行号:699] http://68.1.95.142:5801/v1/models -> Error: HTTPConnectionPool(host='68.1.95.142', port=5801): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A8B0>, 'Connection to 68.1.95.142 timed out. (connect timeout=5)'))
A84 [原始行号:667] http://99.62.52.133:5000/v1/models -> Error: HTTPConnectionPool(host='99.62.52.133', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3310>, 'Connection to 99.62.52.133 timed out. (connect timeout=5)'))
A85 [原始行号:335] http://37.194.195.213:5001/v1/models -> Error: HTTPConnectionPool(host='37.194.195.213', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E742E7F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A86 [原始行号:434] http://73.239.76.231:5000/v1/models -> Error: HTTPConnectionPool(host='73.239.76.231', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0790>, 'Connection to 73.239.76.231 timed out. (connect timeout=5)'))
A87 [原始行号:266] http://95.160.182.178:5001/v1/models -> Error: HTTPConnectionPool(host='95.160.182.178', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F220>, 'Connection to 95.160.182.178 timed out. (connect timeout=5)'))
A88 [原始行号:327] http://71.30.162.2:10002/v1/models -> Error: HTTPConnectionPool(host='71.30.162.2', port=10002): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77DDA60>, 'Connection to 71.30.162.2 timed out. (connect timeout=5)'))
A89 [原始行号:342] http://47.242.245.132:8081/v1/models -> Error: HTTPConnectionPool(host='47.242.245.132', port=8081): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0E50>, 'Connection to 47.242.245.132 timed out. (connect timeout=5)'))
A90 [原始行号:352] http://129.213.85.90:9090/v1/models -> Error: HTTPConnectionPool(host='129.213.85.90', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A34F0>, 'Connection to 129.213.85.90 timed out. (connect timeout=5)'))
A91 [原始行号:30] http://76.31.89.3:5001/v1/models ->   ✅ 成功：响应长度 261 字符
A92 [原始行号:605] http://213.202.211.165:4040/v1/models -> Error: HTTPConnectionPool(host='213.202.211.165', port=4040): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EE370>, 'Connection to 213.202.211.165 timed out. (connect timeout=5)'))
A93 [原始行号:678] http://220.152.100.180:5001/v1/models -> Error: HTTPConnectionPool(host='220.152.100.180', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8C5172F10>, 'Connection to 220.152.100.180 timed out. (connect timeout=5)'))
A94 [原始行号:425] http://104.168.19.243:10000/v1/models -> Error: HTTPConnectionPool(host='104.168.19.243', port=10000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77F8E20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A95 [原始行号:727] http://174.164.84.130:7000/v1/models -> Error: HTTPConnectionPool(host='174.164.84.130', port=7000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8E80>, 'Connection to 174.164.84.130 timed out. (connect timeout=5)'))
A96 [原始行号:399] http://62.224.52.205:8000/v1/models -> Error: HTTPConnectionPool(host='62.224.52.205', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EE400>, 'Connection to 62.224.52.205 timed out. (connect timeout=5)'))
A97 [原始行号:254] http://37.188.82.14:5001/v1/models -> Error: HTTPConnectionPool(host='37.188.82.14', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E780AC10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A98 [原始行号:368] http://150.136.94.213:9090/v1/models -> Error: HTTPConnectionPool(host='150.136.94.213', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3A00>, 'Connection to 150.136.94.213 timed out. (connect timeout=5)'))
A99 [原始行号:133] http://91.156.80.171:5001/v1/models -> Error: HTTPConnectionPool(host='91.156.80.171', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0C70>, 'Connection to 91.156.80.171 timed out. (connect timeout=5)'))
A100 [原始行号:174] http://8.130.123.159:5001/v1/models -> Error: HTTPConnectionPool(host='8.130.123.159', port=5001): Read timed out. (read timeout=5)
A101 [原始行号:607] http://129.213.83.250:9090/v1/models -> Error: HTTPConnectionPool(host='129.213.83.250', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7779280>, 'Connection to 129.213.83.250 timed out. (connect timeout=5)'))
A102 [原始行号:218] http://137.248.121.70:5001/v1/models -> Error: HTTPConnectionPool(host='137.248.121.70', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0F40>, 'Connection to 137.248.121.70 timed out. (connect timeout=5)'))
A103 [原始行号:527] http://118.169.143.75:5001/v1/models -> Error: HTTPConnectionPool(host='118.169.143.75', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3B50>, 'Connection to 118.169.143.75 timed out. (connect timeout=5)'))
A104 [原始行号:84] http://79.134.193.106:5001/v1/models -> Error: HTTPConnectionPool(host='79.134.193.106', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780AB20>, 'Connection to 79.134.193.106 timed out. (connect timeout=5)'))
A105 [原始行号:79] http://115.239.45.69:5001/v1/models -> Error: HTTPConnectionPool(host='115.239.45.69', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77EEEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A106 [原始行号:718] http://123.145.128.239:5001/v1/models -> Error: HTTPConnectionPool(host='123.145.128.239', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F87F0>, 'Connection to 123.145.128.239 timed out. (connect timeout=5)'))
A107 [原始行号:360] http://118.170.43.181:5001/v1/models -> Error: HTTPConnectionPool(host='118.170.43.181', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77F8850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A108 [原始行号:350] http://79.202.96.123:8000/v1/models -> Error: HTTPConnectionPool(host='79.202.96.123', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EEF70>, 'Connection to 79.202.96.123 timed out. (connect timeout=5)'))
A109 [原始行号:572] http://188.191.81.35:5001/v1/models -> Error: HTTPConnectionPool(host='188.191.81.35', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780AB80>, 'Connection to 188.191.81.35 timed out. (connect timeout=5)'))
A110 [原始行号:31] http://68.174.20.252:5001/v1/models -> Error: HTTPConnectionPool(host='68.174.20.252', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3580>, 'Connection to 68.174.20.252 timed out. (connect timeout=5)'))
A111 [原始行号:220] http://50.82.31.57:5001/v1/models -> Error: HTTPConnectionPool(host='50.82.31.57', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A01C0>, 'Connection to 50.82.31.57 timed out. (connect timeout=5)'))
A112 [原始行号:650] http://95.53.185.115:5001/v1/models -> Error: HTTPConnectionPool(host='95.53.185.115', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77E7F70>, 'Connection to 95.53.185.115 timed out. (connect timeout=5)'))
A113 [原始行号:275] http://5.39.216.147:5001/v1/models -> Error: HTTPConnectionPool(host='5.39.216.147', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FBE0>, 'Connection to 5.39.216.147 timed out. (connect timeout=5)'))
A114 [原始行号:629] http://54.184.139.74:8000/v1/models -> Error: HTTPConnectionPool(host='54.184.139.74', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A03D0>, 'Connection to 54.184.139.74 timed out. (connect timeout=5)'))
A115 [原始行号:445] http://37.112.247.63:5001/v1/models -> Error: HTTPConnectionPool(host='37.112.247.63', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3CA0>, 'Connection to 37.112.247.63 timed out. (connect timeout=5)'))
A116 [原始行号:259] http://118.7.243.134:5001/v1/models -> Error: HTTPConnectionPool(host='118.7.243.134', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A8B0>, 'Connection to 118.7.243.134 timed out. (connect timeout=5)'))
A117 [原始行号:55] http://94.231.123.168:5001/v1/models ->   ✅ 成功：响应长度 261 字符
A118 [原始行号:369] http://181.97.214.181:5001/v1/models -> Error: HTTPConnectionPool(host='181.97.214.181', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3CD0>, 'Connection to 181.97.214.181 timed out. (connect timeout=5)'))
A119 [原始行号:196] http://123.145.171.17:8000/v1/models -> Error: HTTPConnectionPool(host='123.145.171.17', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8D90>, 'Connection to 123.145.171.17 timed out. (connect timeout=5)'))
A120 [原始行号:375] http://113.205.28.211:5001/v1/models -> Error: HTTPConnectionPool(host='113.205.28.211', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F0D0>, 'Connection to 113.205.28.211 timed out. (connect timeout=5)'))
A121 [原始行号:468] http://178.49.28.226:5001/v1/models -> Error: HTTPConnectionPool(host='178.49.28.226', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8C5172F10>, 'Connection to 178.49.28.226 timed out. (connect timeout=5)'))
A122 [原始行号:319] http://118.169.163.243:5001/v1/models -> Error: HTTPConnectionPool(host='118.169.163.243', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3340>, 'Connection to 118.169.163.243 timed out. (connect timeout=5)'))
A123 [原始行号:76] http://88.113.95.154:8080/v1/models ->   ✅ 成功：响应长度 265 字符
A124 [原始行号:2] http://150.136.32.85:9090/v1/models -> Error: 401 Client Error: Unauthorized for url: http://150.136.32.85:9090/v1/models
A125 [原始行号:331] http://82.72.241.10:5001/v1/models -> Error: HTTPConnectionPool(host='82.72.241.10', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3760>, 'Connection to 82.72.241.10 timed out. (connect timeout=5)'))
A126 [原始行号:690] http://174.53.187.51:5001/v1/models -> Error: HTTPConnectionPool(host='174.53.187.51', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0520>, 'Connection to 174.53.187.51 timed out. (connect timeout=5)'))
A127 [原始行号:199] http://150.136.38.97:9090/v1/models -> Error: HTTPConnectionPool(host='150.136.38.97', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A00D0>, 'Connection to 150.136.38.97 timed out. (connect timeout=5)'))
A128 [原始行号:314] http://109.226.126.11:5001/v1/models -> Error: HTTPConnectionPool(host='109.226.126.11', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FB20>, 'Connection to 109.226.126.11 timed out. (connect timeout=5)'))
A129 [原始行号:60] http://51.250.121.197:3000/v1/models -> Error: 404 Client Error: Not Found for url: http://51.250.121.197:3000/v1/models/
A130 [原始行号:568] http://132.145.192.28:9090/v1/models -> Error: HTTPConnectionPool(host='132.145.192.28', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A35B0>, 'Connection to 132.145.192.28 timed out. (connect timeout=5)'))
A131 [原始行号:302] http://173.19.1.219:5002/v1/models -> Error: HTTPConnectionPool(host='173.19.1.219', port=5002): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8C51830A0>, 'Connection to 173.19.1.219 timed out. (connect timeout=5)'))
A132 [原始行号:306] http://77.117.99.24:5001/v1/models -> Error: HTTPConnectionPool(host='77.117.99.24', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77EE400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A133 [原始行号:683] http://176.65.44.24:5001/v1/models -> Error: HTTPConnectionPool(host='176.65.44.24', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8A30>, 'Connection to 176.65.44.24 timed out. (connect timeout=5)'))
A134 [原始行号:711] http://89.16.107.184:5001/v1/models -> Error: HTTPConnectionPool(host='89.16.107.184', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79571F0>, 'Connection to 89.16.107.184 timed out. (connect timeout=5)'))
A135 [原始行号:234] http://83.114.86.206:5001/v1/models ->   ✅ 成功：响应长度 261 字符
A136 [原始行号:90] http://109.229.127.151:5001/v1/models -> Error: HTTPConnectionPool(host='109.229.127.151', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EEA60>, 'Connection to 109.229.127.151 timed out. (connect timeout=5)'))
A137 [原始行号:473] http://95.78.108.123:5001/v1/models -> Error: HTTPConnectionPool(host='95.78.108.123', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780AB20>, 'Connection to 95.78.108.123 timed out. (connect timeout=5)'))
A138 [原始行号:469] http://79.241.231.212:8887/v1/models -> Error: HTTPConnectionPool(host='79.241.231.212', port=8887): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3910>, 'Connection to 79.241.231.212 timed out. (connect timeout=5)'))
A139 [原始行号:69] http://5.3.223.150:5001/v1/models -> Error: HTTPConnectionPool(host='5.3.223.150', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77DDC40>, 'Connection to 5.3.223.150 timed out. (connect timeout=5)'))
A140 [原始行号:212] http://213.141.140.52:5001/v1/models -> Error: HTTPConnectionPool(host='213.141.140.52', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A04C0>, 'Connection to 213.141.140.52 timed out. (connect timeout=5)'))
A141 [原始行号:131] http://172.67.167.196:2087/v1/models -> Error: 400 Client Error: Bad Request for url: http://172.67.167.196:2087/v1/models
A142 [原始行号:44] http://109.72.57.7:5001/v1/models ->   ✅ 成功：响应长度 82 字符
A143 [原始行号:70] http://108.82.234.82:5001/v1/models -> Error: HTTPConnectionPool(host='108.82.234.82', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A37F0>, 'Connection to 108.82.234.82 timed out. (connect timeout=5)'))
A144 [原始行号:192] http://64.23.224.64:5001/v1/models -> Error: HTTPConnectionPool(host='64.23.224.64', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3CD0>, 'Connection to 64.23.224.64 timed out. (connect timeout=5)'))
A145 [原始行号:328] http://192.3.204.37:8088/v1/models -> Error: HTTPConnectionPool(host='192.3.204.37', port=8088): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E780ACD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A146 [原始行号:165] http://209.197.88.159:5001/v1/models -> Error: HTTPConnectionPool(host='209.197.88.159', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E77EEEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A147 [原始行号:135] http://211.211.16.66:5001/v1/models -> Error: HTTPConnectionPool(host='211.211.16.66', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8EE0>, 'Connection to 211.211.16.66 timed out. (connect timeout=5)'))
A148 [原始行号:682] http://70.53.13.11:5001/v1/models -> Error: HTTPConnectionPool(host='70.53.13.11', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79676A0>, 'Connection to 70.53.13.11 timed out. (connect timeout=5)'))
A149 [原始行号:250] http://185.146.234.8:8080/v1/models -> Error: HTTPConnectionPool(host='185.146.234.8', port=8080): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E742E760>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A150 [原始行号:336] http://50.39.186.180:5001/v1/models -> Error: HTTPConnectionPool(host='50.39.186.180', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FAC0>, 'Connection to 50.39.186.180 timed out. (connect timeout=5)'))
A151 [原始行号:260] http://2.9.114.39:5001/v1/models -> Error: HTTPConnectionPool(host='2.9.114.39', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8430>, 'Connection to 2.9.114.39 timed out. (connect timeout=5)'))
A152 [原始行号:543] http://24.7.179.239:5001/v1/models -> Error: HTTPConnectionPool(host='24.7.179.239', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3BE0>, 'Connection to 24.7.179.239 timed out. (connect timeout=5)'))
A153 [原始行号:136] http://34.31.132.112:8000/v1/models -> Error: HTTPConnectionPool(host='34.31.132.112', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A38B0>, 'Connection to 34.31.132.112 timed out. (connect timeout=5)'))
A154 [原始行号:215] http://71.67.137.90:5001/v1/models -> Error: HTTPConnectionPool(host='71.67.137.90', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A6A0>, 'Connection to 71.67.137.90 timed out. (connect timeout=5)'))
A155 [原始行号:6] http://129.213.130.79:9090/v1/models -> Error: 401 Client Error: Unauthorized for url: http://129.213.130.79:9090/v1/models
A156 [原始行号:323] http://85.114.183.162:5001/v1/models -> Error: HTTPConnectionPool(host='85.114.183.162', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8760>, 'Connection to 85.114.183.162 timed out. (connect timeout=5)'))
A157 [原始行号:398] http://220.189.110.102:5000/v1/models -> Error: HTTPConnectionPool(host='220.189.110.102', port=5000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E797F550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A158 [原始行号:541] http://74.249.2.162:5000/v1/models -> Error: HTTPConnectionPool(host='74.249.2.162', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7710AF0>, 'Connection to 74.249.2.162 timed out. (connect timeout=5)'))
A159 [原始行号:291] http://123.187.193.141:2024/v1/models -> Error: HTTPConnectionPool(host='123.187.193.141', port=2024): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EE400>, 'Connection to 123.187.193.141 timed out. (connect timeout=5)'))
A160 [原始行号:145] http://61.172.179.12:8062/v1/models -> Error: 404 Client Error: Not Found for url: http://61.172.179.12:8062/v1/models
A161 [原始行号:482] http://71.211.156.220:8051/v1/models -> Error: HTTPConnectionPool(host='71.211.156.220', port=8051): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77EE370>, 'Connection to 71.211.156.220 timed out. (connect timeout=5)'))
A162 [原始行号:132] http://123.145.95.28:8000/v1/models -> Error: HTTPConnectionPool(host='123.145.95.28', port=8000): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A0790>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A163 [原始行号:311] http://129.16.54.41:5001/v1/models -> Error: HTTPConnectionPool(host='129.16.54.41', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7710AF0>, 'Connection to 129.16.54.41 timed out. (connect timeout=5)'))
A164 [原始行号:698] http://216.81.245.14:8090/v1/models -> Error: HTTPConnectionPool(host='216.81.245.14', port=8090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FDF0>, 'Connection to 216.81.245.14 timed out. (connect timeout=5)'))
A165 [原始行号:41] http://74.105.5.31:5001/v1/models -> Error: HTTPConnectionPool(host='74.105.5.31', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8C5116310>, 'Connection to 74.105.5.31 timed out. (connect timeout=5)'))
A166 [原始行号:108] http://97.120.174.69:11434/v1/models -> Error: HTTPConnectionPool(host='97.120.174.69', port=11434): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A36D0>, 'Connection to 97.120.174.69 timed out. (connect timeout=5)'))
A167 [原始行号:439] http://97.113.136.250:5001/v1/models -> Error: HTTPConnectionPool(host='97.113.136.250', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3040>, 'Connection to 97.113.136.250 timed out. (connect timeout=5)'))
A168 [原始行号:56] http://73.73.231.190:5001/v1/models ->   ✅ 成功：响应长度 263 字符
A169 [原始行号:333] http://212.164.221.204:5001/v1/models -> Error: HTTPConnectionPool(host='212.164.221.204', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A3310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A170 [原始行号:208] http://76.141.25.84:5001/v1/models -> Error: HTTPConnectionPool(host='76.141.25.84', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8070>, 'Connection to 76.141.25.84 timed out. (connect timeout=5)'))
A171 [原始行号:598] http://188.191.95.180:5001/v1/models -> Error: HTTPConnectionPool(host='188.191.95.180', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FC70>, 'Connection to 188.191.95.180 timed out. (connect timeout=5)'))
A172 [原始行号:594] http://115.74.39.7:5001/v1/models -> Error: HTTPConnectionPool(host='115.74.39.7', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FE50>, 'Connection to 115.74.39.7 timed out. (connect timeout=5)'))
A173 [原始行号:24] http://68.174.20.252:8000/v1/models -> Error: HTTPConnectionPool(host='68.174.20.252', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E742E790>, 'Connection to 68.174.20.252 timed out. (connect timeout=5)'))
A174 [原始行号:405] http://96.19.99.169:5001/v1/models -> Error: HTTPConnectionPool(host='96.19.99.169', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0A30>, 'Connection to 96.19.99.169 timed out. (connect timeout=5)'))
A175 [原始行号:433] http://119.246.144.140:5001/v1/models -> Error: HTTPConnectionPool(host='119.246.144.140', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F580>, 'Connection to 119.246.144.140 timed out. (connect timeout=5)'))
A176 [原始行号:464] http://123.145.203.51:8000/v1/models -> Error: HTTPConnectionPool(host='123.145.203.51', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F5E0>, 'Connection to 123.145.203.51 timed out. (connect timeout=5)'))
A177 [原始行号:431] http://85.232.130.59:5001/v1/models -> Error: HTTPConnectionPool(host='85.232.130.59', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8DC0>, 'Connection to 85.232.130.59 timed out. (connect timeout=5)'))
A178 [原始行号:538] http://87.97.123.105:5001/v1/models -> Error: HTTPConnectionPool(host='87.97.123.105', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3E50>, 'Connection to 87.97.123.105 timed out. (connect timeout=5)'))
A179 [原始行号:110] http://211.105.223.240:5001/v1/models -> Error: HTTPConnectionPool(host='211.105.223.240', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780AD60>, 'Connection to 211.105.223.240 timed out. (connect timeout=5)'))
A180 [原始行号:82] http://192.210.206.26:8080/v1/models -> Error: 404 Client Error: Not Found for url: http://192.210.206.26:8080/v1/models
A181 [原始行号:51] http://82.28.10.152:5001/v1/models -> Error: HTTPConnectionPool(host='82.28.10.152', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7967AF0>, 'Connection to 82.28.10.152 timed out. (connect timeout=5)'))
A182 [原始行号:522] http://136.52.133.193:5001/v1/models -> Error: HTTPConnectionPool(host='136.52.133.193', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A3970>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A183 [原始行号:585] http://69.248.153.194:5001/v1/models -> Error: HTTPConnectionPool(host='69.248.153.194', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8E50>, 'Connection to 69.248.153.194 timed out. (connect timeout=5)'))
A184 [原始行号:688] http://96.3.152.152:5001/v1/models -> Error: HTTPConnectionPool(host='96.3.152.152', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F220>, 'Connection to 96.3.152.152 timed out. (connect timeout=5)'))
A185 [原始行号:649] http://70.171.77.25:5001/v1/models -> Error: HTTPConnectionPool(host='70.171.77.25', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F730>, 'Connection to 70.171.77.25 timed out. (connect timeout=5)'))
A186 [原始行号:637] http://54.201.168.36:8000/v1/models -> Error: HTTPConnectionPool(host='54.201.168.36', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8C5172FA0>, 'Connection to 54.201.168.36 timed out. (connect timeout=5)'))
A187 [原始行号:525] http://62.68.146.192:5001/v1/models -> Error: HTTPConnectionPool(host='62.68.146.192', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F400>, 'Connection to 62.68.146.192 timed out. (connect timeout=5)'))
A188 [原始行号:367] http://35.232.46.202:8001/v1/models -> Error: HTTPConnectionPool(host='35.232.46.202', port=8001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8E20>, 'Connection to 35.232.46.202 timed out. (connect timeout=5)'))
A189 [原始行号:689] http://125.66.87.4:5555/v1/models -> Error: HTTPConnectionPool(host='125.66.87.4', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3430>, 'Connection to 125.66.87.4 timed out. (connect timeout=5)'))
A190 [原始行号:18] http://108.240.173.188:5001/v1/models -> Error: HTTPConnectionPool(host='108.240.173.188', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79671F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A191 [原始行号:531] http://42.228.19.133:8888/v1/models -> Error: HTTPConnectionPool(host='42.228.19.133', port=8888): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A0850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A192 [原始行号:411] http://158.101.126.47:9090/v1/models -> Error: HTTPConnectionPool(host='158.101.126.47', port=9090): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A5280>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A193 [原始行号:292] http://79.247.228.103:8001/v1/models -> Error: HTTPConnectionPool(host='79.247.228.103', port=8001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E780A790>, 'Connection to 79.247.228.103 timed out. (connect timeout=5)'))
A194 [原始行号:481] http://94.143.44.33:5001/v1/models -> Error: HTTPConnectionPool(host='94.143.44.33', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3910>, 'Connection to 94.143.44.33 timed out. (connect timeout=5)'))
A195 [原始行号:83] http://123.187.193.143:2024/v1/models -> Error: HTTPConnectionPool(host='123.187.193.143', port=2024): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F80A0>, 'Connection to 123.187.193.143 timed out. (connect timeout=5)'))
A196 [原始行号:61] http://86.38.238.20:2222/v1/models -> Error: HTTPConnectionPool(host='86.38.238.20', port=2222): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797FAF0>, 'Connection to 86.38.238.20 timed out. (connect timeout=5)'))
A197 [原始行号:204] http://150.136.94.99:9090/v1/models -> Error: HTTPConnectionPool(host='150.136.94.99', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5A00>, 'Connection to 150.136.94.99 timed out. (connect timeout=5)'))
A198 [原始行号:424] http://88.113.95.92:8080/v1/models -> Error: HTTPConnectionPool(host='88.113.95.92', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A43A0>, 'Connection to 88.113.95.92 timed out. (connect timeout=5)'))
A199 [原始行号:29] http://85.89.177.64:5001/v1/models -> Error: HTTPConnectionPool(host='85.89.177.64', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F760>, 'Connection to 85.89.177.64 timed out. (connect timeout=5)'))
A200 [原始行号:231] http://122.209.198.131:5001/v1/models -> Error: HTTPConnectionPool(host='122.209.198.131', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8760>, 'Connection to 122.209.198.131 timed out. (connect timeout=5)'))
A201 [原始行号:213] http://82.208.122.193:5001/v1/models -> Error: HTTPConnectionPool(host='82.208.122.193', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3250>, 'Connection to 82.208.122.193 timed out. (connect timeout=5)'))
A202 [原始行号:487] http://47.108.59.220:5001/v1/models -> Error: HTTPConnectionPool(host='47.108.59.220', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79671F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A203 [原始行号:712] http://5.164.178.109:5001/v1/models -> Error: HTTPConnectionPool(host='5.164.178.109', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5400>, 'Connection to 5.164.178.109 timed out. (connect timeout=5)'))
A204 [原始行号:182] http://129.213.92.30:9090/v1/models -> Error: HTTPConnectionPool(host='129.213.92.30', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0F40>, 'Connection to 129.213.92.30 timed out. (connect timeout=5)'))
A205 [原始行号:626] http://35.90.166.44:8000/v1/models -> Error: HTTPConnectionPool(host='35.90.166.44', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3820>, 'Connection to 35.90.166.44 timed out. (connect timeout=5)'))
A206 [原始行号:248] http://132.145.194.137:9090/v1/models -> Error: HTTPConnectionPool(host='132.145.194.137', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8970>, 'Connection to 132.145.194.137 timed out. (connect timeout=5)'))
A207 [原始行号:518] http://75.102.210.25:5001/v1/models -> Error: HTTPConnectionPool(host='75.102.210.25', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E797FE50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A208 [原始行号:362] http://76.83.128.162:5001/v1/models -> Error: HTTPConnectionPool(host='76.83.128.162', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F730>, 'Connection to 76.83.128.162 timed out. (connect timeout=5)'))
A209 [原始行号:664] http://95.53.166.34:5001/v1/models -> Error: HTTPConnectionPool(host='95.53.166.34', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A56A0>, 'Connection to 95.53.166.34 timed out. (connect timeout=5)'))
A210 [原始行号:549] http://171.232.54.48:5001/v1/models -> Error: HTTPConnectionPool(host='171.232.54.48', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A4340>, 'Connection to 171.232.54.48 timed out. (connect timeout=5)'))
A211 [原始行号:654] http://73.113.76.129:5001/v1/models -> Error: HTTPConnectionPool(host='73.113.76.129', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F700>, 'Connection to 73.113.76.129 timed out. (connect timeout=5)'))
A212 [原始行号:209] http://115.79.231.122:5001/v1/models -> Error: HTTPConnectionPool(host='115.79.231.122', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F370>, 'Connection to 115.79.231.122 timed out. (connect timeout=5)'))
A213 [原始行号:450] http://82.15.22.216:5001/v1/models -> Error: HTTPConnectionPool(host='82.15.22.216', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F89D0>, 'Connection to 82.15.22.216 timed out. (connect timeout=5)'))
A214 [原始行号:408] http://217.69.111.142:5001/v1/models -> Error: HTTPConnectionPool(host='217.69.111.142', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3B80>, 'Connection to 217.69.111.142 timed out. (connect timeout=5)'))
A215 [原始行号:176] http://81.233.240.60:5001/v1/models -> Error: HTTPConnectionPool(host='81.233.240.60', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E7967EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A216 [原始行号:299] http://27.12.111.3:8000/v1/models -> Error: HTTPConnectionPool(host='27.12.111.3', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A4D90>, 'Connection to 27.12.111.3 timed out. (connect timeout=5)'))
A217 [原始行号:516] http://126.42.27.234:5001/v1/models -> Error: HTTPConnectionPool(host='126.42.27.234', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A3580>, 'Connection to 126.42.27.234 timed out. (connect timeout=5)'))
A218 [原始行号:533] http://76.214.46.35:5001/v1/models -> Error: HTTPConnectionPool(host='76.214.46.35', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77F8250>, 'Connection to 76.214.46.35 timed out. (connect timeout=5)'))
A219 [原始行号:264] http://117.158.186.213:5001/v1/models -> Error: HTTPConnectionPool(host='117.158.186.213', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E797F220>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A220 [原始行号:137] http://91.204.168.194:5001/v1/models -> Error: HTTPConnectionPool(host='91.204.168.194', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A54F0>, 'Connection to 91.204.168.194 timed out. (connect timeout=5)'))
A221 [原始行号:223] http://45.151.153.9:5001/v1/models -> Error: HTTPConnectionPool(host='45.151.153.9', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A4580>, 'Connection to 45.151.153.9 timed out. (connect timeout=5)'))
A222 [原始行号:684] http://46.0.65.117:5001/v1/models -> Error: HTTPConnectionPool(host='46.0.65.117', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79B2730>, 'Connection to 46.0.65.117 timed out. (connect timeout=5)'))
A223 [原始行号:685] http://150.136.146.14:9090/v1/models -> Error: HTTPConnectionPool(host='150.136.146.14', port=9090): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A47F0>, 'Connection to 150.136.146.14 timed out. (connect timeout=5)'))
A224 [原始行号:163] http://8.130.123.159:5001/v1/models -> Error: HTTPConnectionPool(host='8.130.123.159', port=5001): Read timed out. (read timeout=5)
A225 [原始行号:394] http://125.66.87.182:5555/v1/models -> Error: HTTPConnectionPool(host='125.66.87.182', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5130>, 'Connection to 125.66.87.182 timed out. (connect timeout=5)'))
A226 [原始行号:641] http://114.130.36.121:5001/v1/models -> Error: HTTPConnectionPool(host='114.130.36.121', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77DDB50>, 'Connection to 114.130.36.121 timed out. (connect timeout=5)'))
A227 [原始行号:490] http://85.64.155.48:5001/v1/models -> Error: HTTPConnectionPool(host='85.64.155.48', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F460>, 'Connection to 85.64.155.48 timed out. (connect timeout=5)'))
A228 [原始行号:390] http://35.239.146.85:8000/v1/models -> Error: HTTPConnectionPool(host='35.239.146.85', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0490>, 'Connection to 35.239.146.85 timed out. (connect timeout=5)'))
A229 [原始行号:371] http://188.25.211.147:5001/v1/models -> Error: HTTPConnectionPool(host='188.25.211.147', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7779940>, 'Connection to 188.25.211.147 timed out. (connect timeout=5)'))
A230 [原始行号:334] http://111.235.222.73:5001/v1/models -> Error: HTTPConnectionPool(host='111.235.222.73', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F640>, 'Connection to 111.235.222.73 timed out. (connect timeout=5)'))
A231 [原始行号:457] http://123.145.107.81:8000/v1/models -> Error: HTTPConnectionPool(host='123.145.107.81', port=8000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A47C0>, 'Connection to 123.145.107.81 timed out. (connect timeout=5)'))
A232 [原始行号:104] http://95.31.13.32:5001/v1/models -> Error: HTTPConnectionPool(host='95.31.13.32', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5A30>, 'Connection to 95.31.13.32 timed out. (connect timeout=5)'))
A233 [原始行号:114] http://50.39.235.57:5001/v1/models ->   ✅ 成功：响应长度 257 字符
A234 [原始行号:656] http://65.101.238.110:5001/v1/models -> Error: HTTPConnectionPool(host='65.101.238.110', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5850>, 'Connection to 65.101.238.110 timed out. (connect timeout=5)'))
A235 [原始行号:239] http://123.187.193.36:2024/v1/models -> Error: HTTPConnectionPool(host='123.187.193.36', port=2024): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0970>, 'Connection to 123.187.193.36 timed out. (connect timeout=5)'))
A236 [原始行号:655] http://125.66.80.123:5555/v1/models -> Error: HTTPConnectionPool(host='125.66.80.123', port=5555): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5C10>, 'Connection to 125.66.80.123 timed out. (connect timeout=5)'))
A237 [原始行号:294] http://89.110.53.234:5001/v1/models -> Error: HTTPConnectionPool(host='89.110.53.234', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A4820>, 'Connection to 89.110.53.234 timed out. (connect timeout=5)'))
A238 [原始行号:92] http://5.164.178.172:5001/v1/models -> Error: HTTPConnectionPool(host='5.164.178.172', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F3A0>, 'Connection to 5.164.178.172 timed out. (connect timeout=5)'))
A239 [原始行号:7] http://150.136.216.65:9090/v1/models -> Error: 401 Client Error: Unauthorized for url: http://150.136.216.65:9090/v1/models
A240 [原始行号:89] http://176.158.149.107:5001/v1/models ->   ✅ 成功：响应长度 83 字符
A241 [原始行号:554] http://188.165.195.18:5001/v1/models -> Error: HTTPConnectionPool(host='188.165.195.18', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7967A00>, 'Connection to 188.165.195.18 timed out. (connect timeout=5)'))
A242 [原始行号:393] http://36.103.167.227:8080/v1/models -> Error: HTTPConnectionPool(host='36.103.167.227', port=8080): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8C51831C0>, 'Connection to 36.103.167.227 timed out. (connect timeout=5)'))
A243 [原始行号:670] http://180.171.253.221:5001/v1/models -> Error: HTTPConnectionPool(host='180.171.253.221', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0310>, 'Connection to 180.171.253.221 timed out. (connect timeout=5)'))
A244 [原始行号:677] http://35.184.242.221:3000/v1/models -> Error: HTTPConnectionPool(host='35.184.242.221', port=3000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E77DDAC0>, 'Connection to 35.184.242.221 timed out. (connect timeout=5)'))
A245 [原始行号:590] http://172.208.112.23:5000/v1/models -> Error: HTTPConnectionPool(host='172.208.112.23', port=5000): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A4880>, 'Connection to 172.208.112.23 timed out. (connect timeout=5)'))
A246 [原始行号:547] http://72.18.81.105:8090/v1/models -> Error: HTTPConnectionPool(host='72.18.81.105', port=8090): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A4E50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A247 [原始行号:420] http://82.65.44.235:5001/v1/models -> Error: HTTPConnectionPool(host='82.65.44.235', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E7967CA0>, 'Connection to 82.65.44.235 timed out. (connect timeout=5)'))
A248 [原始行号:409] http://77.3.210.105:5001/v1/models -> Error: HTTPConnectionPool(host='77.3.210.105', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A0A60>, 'Connection to 77.3.210.105 timed out. (connect timeout=5)'))
A249 [原始行号:11] http://8.137.87.44:3000/v1/models -> Error: 404 Client Error: Not Found for url: http://8.137.87.44:3000/v1/models
A250 [原始行号:140] http://47.159.155.215:5001/v1/models -> Error: HTTPConnectionPool(host='47.159.155.215', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A5100>, 'Connection to 47.159.155.215 timed out. (connect timeout=5)'))
A251 [原始行号:28] http://185.83.95.42:5001/v1/models -> Error: HTTPConnectionPool(host='185.83.95.42', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E79A4580>, 'Connection to 185.83.95.42 timed out. (connect timeout=5)'))
A252 [原始行号:43] http://176.99.74.73:5001/v1/models -> Error: HTTPConnectionPool(host='176.99.74.73', port=5001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B8E79A48E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
A253 [原始行号:42] http://109.173.32.130:5001/v1/models -> Error: HTTPConnectionPool(host='109.173.32.130', port=5001): Max retries exceeded with url: /v1/models (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002B8E797F640>, 'Connection to 109.173.32.130 timed out. (connect timeout=5)'))
